import type { Activity, Album } from './types';

export const activities: Activity[] = [
  {
    id: '1',
    title: 'Science Fair Extravaganza',
    titleAr: 'معرض العلوم المذهل',
    description: 'Showcase your scientific prowess in our annual science fair. Prizes for the most innovative projects!',
    descriptionAr: 'أظهر براعتك العلمية في معرضنا العلمي السنوي. جوائز للمشاريع الأكثر ابتكارًا!',
    category: 'Event',
    date: '2024-10-15',
    time: '09:00 - 15:00',
    location: 'Main Auditorium',
    locationAr: 'القاعة الرئيسية',
    cost: 0,
    imageUrl: 'https://picsum.photos/600/400?random=1',
    imageHint: 'science experiment'
  },
  {
    id: '2',
    title: 'Varsity Basketball Finals',
    titleAr: 'نهائيات كرة السلة للمنتخب',
    description: 'Cheer for our home team as they battle for the championship title. Go Eagles!',
    descriptionAr: 'شجع فريقنا وهو يقاتل من أجل لقب البطولة. هيا يا نسور!',
    category: 'Event',
    date: '2024-10-22',
    time: '18:00 - 20:00',
    location: 'Gymnasium',
    locationAr: 'صالة الألعاب الرياضية',
    cost: 5,
    imageUrl: 'https://picsum.photos/600/400?random=2',
    imageHint: 'basketball game'
  },
  {
    id: '3',
    title: 'Museum of Natural History Trip',
    titleAr: 'رحلة إلى متحف التاريخ الطبيعي',
    description: 'A trip to explore the wonders of the natural world. Limited spots available.',
    descriptionAr: 'رحلة لاستكشاف عجائب العالم الطبيعي. الأماكن محدودة.',
    category: 'Trip',
    date: '2024-11-05',
    time: '08:00 - 16:00',
    location: 'City Museum',
    locationAr: 'متحف المدينة',
    cost: 25,
    imageUrl: 'https://picsum.photos/600/400?random=3',
    imageHint: 'museum interior'
  },
  {
    id: '4',
    title: 'Coding Club Weekly Meetup',
    titleAr: 'لقاء نادي البرمجة الأسبوعي',
    description: 'Join us to learn new coding skills, work on projects, and collaborate with peers.',
    descriptionAr: 'انضم إلينا لتعلم مهارات برمجة جديدة والعمل على مشاريع والتعاون مع الزملاء.',
    category: 'Free',
    date: 'Every Wednesday',
    time: '15:00 - 16:30',
    location: 'Computer Lab 2',
    locationAr: 'مختبر الحاسوب 2',
    cost: 0,
    imageUrl: 'https://picsum.photos/600/400?random=4',
    imageHint: 'students coding'
  },
  {
    id: '5',
    title: 'Advanced Pottery Workshop',
    titleAr: 'ورشة عمل الفخار المتقدمة',
    description: 'Master the wheel and advanced glazing techniques in this intensive workshop series.',
    descriptionAr: 'أتقن عجلة الفخار وتقنيات التزجيج المتقدمة في سلسلة ورش العمل المكثفة هذه.',
    category: 'Paid',
    date: 'Saturdays, Nov 2 - Dec 14',
    time: '10:00 - 13:00',
    location: 'Art Studio',
    locationAr: 'استوديو الفن',
    cost: 120,
    imageUrl: 'https://picsum.photos/600/400?random=5',
    imageHint: 'pottery wheel'
  },
  {
    id: '6',
    title: 'School Play: "A Midsummer Night\'s Dream"',
    titleAr: 'مسرحية المدرسة: "حلم ليلة صيف"',
    description: 'Experience Shakespeare like never before in our drama club\'s flagship production of the year.',
    descriptionAr: 'اختبر شكسبير كما لم يحدث من قبل في الإنتاج الرئيسي لنادي الدراما لهذا العام.',
    category: 'Event',
    date: '2024-11-20',
    time: '19:00 - 21:00',
    location: 'Performing Arts Center',
    locationAr: 'مركز الفنون الأدائية',
    cost: 10,
    imageUrl: 'https://picsum.photos/600/400?random=6',
    imageHint: 'theatre stage'
  }
];

export const albums: Album[] = [
  {
    id: 'album1',
    title: 'Science Fair 2023',
    titleAr: 'معرض العلوم ٢٠٢٣',
    description: 'A collection of photos from our spectacular annual Science Fair.',
    descriptionAr: 'مجموعة صور من معرضنا العلمي السنوي المذهل.',
    category: 'Academics',
    coverImageUrl: 'https://picsum.photos/600/400?random=7',
    coverImageHint: 'student presentation',
    photos: [
      { id: 'p1', url: 'https://picsum.photos/800/600?random=8', alt: 'Volcano project', altAr: 'مشروع بركان', hint: 'volcano project' },
      { id: 'p2', url: 'https://picsum.photos/800/600?random=9', alt: 'Students with medals', altAr: 'طلاب مع ميداليات', hint: 'students medals' },
      { id: 'p3', url: 'https://picsum.photos/800/600?random=10', alt: 'Robotics demonstration', altAr: 'عرض روبوتات', hint: 'robotics demonstration' },
      { id: 'p4', url: 'https://picsum.photos/800/600?random=11', alt: 'Judges inspecting a project', altAr: 'الحكام يتفقدون مشروعًا', hint: 'judges project' },
    ],
  },
  {
    id: 'album2',
    title: 'Championship Basketball Game',
    titleAr: 'مباراة بطولة كرة السلة',
    description: 'Action shots from the thrilling final game.',
    descriptionAr: 'لقطات حماسية من المباراة النهائية المثيرة.',
    category: 'Sports',
    coverImageUrl: 'https://picsum.photos/600/400?random=12',
    coverImageHint: 'basketball court',
    photos: [
      { id: 'p5', url: 'https://picsum.photos/800/600?random=13', alt: 'Slam dunk', altAr: 'سلام دانك', hint: 'slam dunk' },
      { id: 'p6', url: 'https://picsum.photos/800/600?random=14', alt: 'Team celebrating victory', altAr: 'الفريق يحتفل بالفوز', hint: 'team celebration' },
      { id: 'p7', url: 'https://picsum.photos/800/600?random=15', alt: 'Fans cheering', altAr: 'الجماهير تهتف', hint: 'fans cheering' },
    ],
  },
  {
    id: 'album3',
    title: 'Annual School Play',
    titleAr: 'المسرحية المدرسية السنوية',
    description: 'Behind the scenes and on-stage photos from this year\'s drama production.',
    descriptionAr: 'صور من خلف الكواليس وعلى المسرح من إنتاج الدراما لهذا العام.',
    category: 'Events',
    coverImageUrl: 'https://picsum.photos/600/400?random=16',
    coverImageHint: 'stage actors',
    photos: [
      { id: 'p8', url: 'https://picsum.photos/800/600?random=17', alt: 'Actors in costume', altAr: 'ممثلون بأزيائهم', hint: 'actors costume' },
      { id: 'p9', url: 'https://picsum.photos/800/600?random=18', alt: 'Final bow', altAr: 'الانحناءة الأخيرة', hint: 'final bow' },
      { id: 'p10', url: 'https://picsum.photos/800/600?random=19', alt: 'Stage set', altAr: 'ديكور المسرح', hint: 'stage set' },
      { id: 'p11', url: 'https://picsum.photos/800/600?random=20', alt: 'Director with cast', altAr: 'المخرج مع طاقم التمثيل', hint: 'director cast' },
    ],
  },
  {
    id: 'album4',
    title: 'Trip to the Capital',
    titleAr: 'رحلة إلى العاصمة',
    description: 'Exploring the landmarks and history of our nation\'s capital.',
    descriptionAr: 'استكشاف معالم وتاريخ عاصمة بلادنا.',
    category: 'Trips',
    coverImageUrl: 'https://picsum.photos/600/400?random=21',
    coverImageHint: 'city landmark',
    photos: [
      { id: 'p12', url: 'https://picsum.photos/800/600?random=22', alt: 'Students at the parliament building', altAr: 'طلاب عند مبنى البرلمان', hint: 'students parliament' },
      { id: 'p13', url: 'https://picsum.photos/800/600?random=23', alt: 'Group photo at a monument', altAr: 'صورة جماعية عند نصب تذكاري', hint: 'group monument' },
    ],
  },
];
